project:
  type: website
  output-dir: docs
  resources:
    - "modulo_1/galton_sim.html"

website:
  title: "Academy Statistica"
  sidebar:
    contents:
      - index.qmd
      - modulo_1/lecture_1.qmd
      - modulo_1/lecture_2.qmd
      - modulo_1/lecture_3.qmd

format:
  html:
    theme: cosmo
