project:
  type: website
  output-dir: docs

website:
  title: "Academy Statistica"
  sidebar:
    contents:
      - index.qmd
      - modulo_1/lecture_1.qmd
      - modulo_1/lecture_2.qmd

format:
  html:
    theme: cosmo
