name: Render and Publish Quarto Website

on:
  push:
    branches: [ main, master ] # Si attiva quando salvi su questi rami

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/ # Quarto deve essere impostato per scrivere qui nel file _quarto.yml

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
